name: CI

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Launch MCC
        env:
          PASSWD: ${{ secrets.PASSWD }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          bash launch.sh
