name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 */6 * * *" # in UTC time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Launch MCC
        env:
          PASSWD: ${{ secrets.PASSWD }}
        run: |
          bash launch.sh
